### ISSUE TITLE
FindRoutes ExecuteError

### ISSUE THREAD

**Issue by pust777** [Esri/network-analysis-services#24]
I'm using v2.1 and am using these parameters. What am I doing wrong? Desktop and server are on the same machine.
![image001](https://user-images.githubusercontent.com/2235987/38838675-f6854328-419c-11e8-81ca-b6a5767a6b02.png)

-NetworkAnalysis_NAserver.sd is created
-NetworkAnalysisUtilities_GPServer.sd is created

> ERROR | 2018-04-16 15:40:33 | GPMessageFileLogger | nas | exception | 352 | A geoprocessing error occurred. Details have been logged to C:\SD_files\PublishRoutingServices.log
Traceback (most recent call last):
  File "<string>", line 280, in execute
  File "C:\Users\COGIS001\Desktop\network-analysis-services-master\ut.py", line 1061, in execute
    find_routes_result = nast.FindRoutes(rt_stops, "Minutes", supporting_files_folder)
  File "C:\Users\COGIS001\Desktop\network-analysis-services-master\NetworkAnalysisTools.pyt", line 3989, >in FindRoutes ExecuteError: Failed to execute. Parameters are not valid.
The network dataset Routing_ND is referenced with a catalog path instead of a network dataset layer
Failed to execute (FindRoutes).

**Comment by pust777** [comment]
Ran script tool from separate desktop. FindRoutesError does not show up. All .sd files created bu receive a upload service definition error. Closing this for now
