### ISSUE TITLE
Analyze Network Dataset Fails

### ISSUE THREAD

**Issue by vsmith1987** [Esri/network-analysis-services#25]
When trying to execute the Analyze Network Dataset Tool, the following error occurs:
Executing: AnalyzeNetworkDataset "\\Coangisd\gis\GIS\ArcGIS\GeoDatabases\Network Dataset\NetworkDataset.gdb\Transportation\Centerlines_ND"
Start Time: Wed May 08 10:29:18 2019
Running script AnalyzeNetworkDataset...

Traceback (most recent call last):
  File "<string>", line 349, in execute
  File "D:\ArcGIS\Toolboxes\network-analysis-services-2.1\ut.py", line 1473, in __init__
    self.descNDS = arcpy.Describe(network_dataset)
AttributeError: 'module' object has no attribute 'Describe'

Failed to execute (AnalyzeNetworkDataset).
Failed at Wed May 08 10:29:18 2019 (Elapsed Time: 0.00 seconds)

I'm unsure as to where or what this is.

**Comment by deelesh** [comment]
@vsmith1987 
The error `AttributeError: 'module' object has no attribute 'Describe'` hints at something being incorrect with arcpy in your environment.

Having said that, if you had issues related to arcpy not being correctly installed, The PublishRoutingServices tool should not have reached so far in the execution and failed when analyzing the network dataset.

Which version of ArcGIS you are trying to run this with?

**Comment by vsmith1987** [comment]
Deelesh,

Haven’t had any issues with any other python code that runs.
Haven’t run the Publish Routing Services Tool, just the Analyze Network Dataset Tool first (as per the instructions).
We are at version 10.5.1.

Thank You,
[cid:image001.png@01D379AD.7AC6AC20]

Vince Smith, GISP
GIS Manager
Information Technology Division
City of Aurora
44 E. Downer Place
Aurora, IL  60507
Office: 630-256-3474
Cell: 630-688-2021
vsmith@aurora-il.org
www.aurora-il.org<http://www.aurora-il.org/>
